- src: https://github.com/geerlingguy/ansible-role-packer
  name: geerlingguy.packer

- src: https://github.com/geerlingguy/ansible-role-jenkins
  name: geerlingguy.jenkins

- src: https://github.com/geerlingguy/ansible-role-java
  name: geerlingguy.java